import type { Metadata } from "next";
import { Roboto, Poppins, Lora, Lobster_Two } from 'next/font/google';
import "./globals.css";
import Footer from "@/components/global/Footer";
import Navbar from "@/components/global/Navbar";
import { ThemeProvider } from "@/components/theme-provider"

const roboto = Lora({
  variable: "--font-roboto",
  subsets: ['latin', 'latin-ext'],
  weight: ['400', '500',  '700',],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       
      <body
        className={`${roboto.variable} antialiased`}
      >
      <ThemeProvider
					attribute="class"
					defaultTheme="dark"
					enableSystem
					disableTransitionOnChange>
        <Navbar />
        {children}
        <Footer />
        </ThemeProvider>
      </body>
      
    </html>
  );
}
